/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sites: Site;
    articles: Article;
    'site-navigation': SiteNavigation;
    'site-faq': SiteFaq;
    'site-instruments': SiteInstrument;
    'site-accounts': SiteAccount;
    'site-promotions': SitePromotion;
    'site-partners': SitePartner;
    'site-academy': SiteAcademy;
    'site-streams': SiteStream;
    'site-contacts': SiteContact;
    'site-careers': SiteCareer;
    'site-legal': SiteLegal;
    'site-system-status': SiteSystemStatus;
    'site-cabinet-home': SiteCabinetHome;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'site-navigation': SiteNavigationSelect<false> | SiteNavigationSelect<true>;
    'site-faq': SiteFaqSelect<false> | SiteFaqSelect<true>;
    'site-instruments': SiteInstrumentsSelect<false> | SiteInstrumentsSelect<true>;
    'site-accounts': SiteAccountsSelect<false> | SiteAccountsSelect<true>;
    'site-promotions': SitePromotionsSelect<false> | SitePromotionsSelect<true>;
    'site-partners': SitePartnersSelect<false> | SitePartnersSelect<true>;
    'site-academy': SiteAcademySelect<false> | SiteAcademySelect<true>;
    'site-streams': SiteStreamsSelect<false> | SiteStreamsSelect<true>;
    'site-contacts': SiteContactsSelect<false> | SiteContactsSelect<true>;
    'site-careers': SiteCareersSelect<false> | SiteCareersSelect<true>;
    'site-legal': SiteLegalSelect<false> | SiteLegalSelect<true>;
    'site-system-status': SiteSystemStatusSelect<false> | SiteSystemStatusSelect<true>;
    'site-cabinet-home': SiteCabinetHomeSelect<false> | SiteCabinetHomeSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  slug: string;
  name: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  primaryColor: string;
  socials?:
    | {
        name: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  demoStartBalanceCents: number;
  /**
   * Пусто — используется SITE_WEBHOOK_URL из окружения
   */
  webhookUrl?: string | null;
  /**
   * Пусто — используется SITE_WEBHOOK_SECRET из окружения
   */
  webhookSecret?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  site: number | Site;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  source: string;
  publishedAt: string;
  readingMinutes: number;
  bodyMarkdown: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation".
 */
export interface SiteNavigation {
  id: number;
  site: number | Site;
  header?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  riskWarning: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-faq".
 */
export interface SiteFaq {
  id: number;
  site: number | Site;
  sections?:
    | {
        title: string;
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-instruments".
 */
export interface SiteInstrument {
  id: number;
  site: number | Site;
  items?:
    | {
        symbol: string;
        name: string;
        category: 'forex' | 'metals' | 'crypto' | 'indices' | 'stocks' | 'energy';
        digits: number;
        leverageMax: string;
        spreadFrom: string;
        swapFree?: boolean | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-accounts".
 */
export interface SiteAccount {
  id: number;
  site: number | Site;
  items?:
    | {
        planId: string;
        name: string;
        description: string;
        minDeposit: string;
        featured?: boolean | null;
        features?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        pricing: {
          spreadPips: number;
          commissionPerLotRT: number;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-promotions".
 */
export interface SitePromotion {
  id: number;
  site: number | Site;
  items?:
    | {
        promoId: string;
        badge: string;
        title: string;
        description: string;
        terms: string;
        ctaLabel: string;
        ctaHref: string;
        featured?: boolean | null;
        activeFrom?: string | null;
        activeTo?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-partners".
 */
export interface SitePartner {
  id: number;
  site: number | Site;
  models?:
    | {
        name: string;
        description: string;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tiers?:
    | {
        name: string;
        clients: string;
        share: string;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-academy".
 */
export interface SiteAcademy {
  id: number;
  site: number | Site;
  articles?:
    | {
        slug: string;
        title: string;
        excerpt: string;
        level: 'beginner' | 'intermediate';
        readingMinutes: number;
        bodyMarkdown: string;
        id?: string | null;
      }[]
    | null;
  webinars?:
    | {
        webinarId: string;
        title: string;
        speaker: string;
        speakerRole: string;
        startsAt: string;
        durationMinutes: number;
        level: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  glossary?:
    | {
        term: string;
        definition: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-streams".
 */
export interface SiteStream {
  id: number;
  site: number | Site;
  items?:
    | {
        provider: 'youtube' | 'vimeo';
        videoId: string;
        title: string;
        poster?: (number | null) | Media;
        startsAt: string;
        status: 'live' | 'upcoming' | 'past';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contacts".
 */
export interface SiteContact {
  id: number;
  site: number | Site;
  channels?:
    | {
        title: string;
        value: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  offices?:
    | {
        city: string;
        country: string;
        address: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-careers".
 */
export interface SiteCareer {
  id: number;
  site: number | Site;
  benefits?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  vacancies?:
    | {
        title: string;
        department: string;
        location: string;
        type: string;
        applyEmail: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-legal".
 */
export interface SiteLegal {
  id: number;
  site: number | Site;
  items?:
    | {
        slug: string;
        title: string;
        updatedAt: string;
        intro: string;
        sections?:
          | {
              heading: string;
              paragraphsMarkdown?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-system-status".
 */
export interface SiteSystemStatus {
  id: number;
  site: number | Site;
  services?:
    | {
        serviceId: string;
        name: string;
        description: string;
        status: 'operational' | 'degraded' | 'outage' | 'maintenance';
        uptime90d: string;
        id?: string | null;
      }[]
    | null;
  incidents?:
    | {
        date: string;
        title: string;
        status: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-cabinet-home".
 */
export interface SiteCabinetHome {
  id: number;
  site: number | Site;
  modules?:
    | {
        type: 'profile' | 'onboarding' | 'balance' | 'markets' | 'promotions';
        enabled?: boolean | null;
        steps?: {
          verification?: boolean | null;
          deposit?: boolean | null;
          firstTrade?: boolean | null;
        };
        buttons?: {
          deposit?: boolean | null;
          withdraw?: boolean | null;
          buyFiat?: boolean | null;
        };
        tabs?: {
          assets?: boolean | null;
          popular?: boolean | null;
          newListing?: boolean | null;
          favorites?: boolean | null;
          gainers?: boolean | null;
          volume?: boolean | null;
        };
        newListingSymbols?:
          | {
              symbol: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'site-navigation';
        value: number | SiteNavigation;
      } | null)
    | ({
        relationTo: 'site-faq';
        value: number | SiteFaq;
      } | null)
    | ({
        relationTo: 'site-instruments';
        value: number | SiteInstrument;
      } | null)
    | ({
        relationTo: 'site-accounts';
        value: number | SiteAccount;
      } | null)
    | ({
        relationTo: 'site-promotions';
        value: number | SitePromotion;
      } | null)
    | ({
        relationTo: 'site-partners';
        value: number | SitePartner;
      } | null)
    | ({
        relationTo: 'site-academy';
        value: number | SiteAcademy;
      } | null)
    | ({
        relationTo: 'site-streams';
        value: number | SiteStream;
      } | null)
    | ({
        relationTo: 'site-contacts';
        value: number | SiteContact;
      } | null)
    | ({
        relationTo: 'site-careers';
        value: number | SiteCareer;
      } | null)
    | ({
        relationTo: 'site-legal';
        value: number | SiteLegal;
      } | null)
    | ({
        relationTo: 'site-system-status';
        value: number | SiteSystemStatus;
      } | null)
    | ({
        relationTo: 'site-cabinet-home';
        value: number | SiteCabinetHome;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  favicon?: T;
  primaryColor?: T;
  socials?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  demoStartBalanceCents?: T;
  webhookUrl?: T;
  webhookSecret?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  site?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  category?: T;
  source?: T;
  publishedAt?: T;
  readingMinutes?: T;
  bodyMarkdown?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation_select".
 */
export interface SiteNavigationSelect<T extends boolean = true> {
  site?: T;
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  riskWarning?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-faq_select".
 */
export interface SiteFaqSelect<T extends boolean = true> {
  site?: T;
  sections?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-instruments_select".
 */
export interface SiteInstrumentsSelect<T extends boolean = true> {
  site?: T;
  items?:
    | T
    | {
        symbol?: T;
        name?: T;
        category?: T;
        digits?: T;
        leverageMax?: T;
        spreadFrom?: T;
        swapFree?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-accounts_select".
 */
export interface SiteAccountsSelect<T extends boolean = true> {
  site?: T;
  items?:
    | T
    | {
        planId?: T;
        name?: T;
        description?: T;
        minDeposit?: T;
        featured?: T;
        features?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        pricing?:
          | T
          | {
              spreadPips?: T;
              commissionPerLotRT?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-promotions_select".
 */
export interface SitePromotionsSelect<T extends boolean = true> {
  site?: T;
  items?:
    | T
    | {
        promoId?: T;
        badge?: T;
        title?: T;
        description?: T;
        terms?: T;
        ctaLabel?: T;
        ctaHref?: T;
        featured?: T;
        activeFrom?: T;
        activeTo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-partners_select".
 */
export interface SitePartnersSelect<T extends boolean = true> {
  site?: T;
  models?:
    | T
    | {
        name?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  tiers?:
    | T
    | {
        name?: T;
        clients?: T;
        share?: T;
        featured?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-academy_select".
 */
export interface SiteAcademySelect<T extends boolean = true> {
  site?: T;
  articles?:
    | T
    | {
        slug?: T;
        title?: T;
        excerpt?: T;
        level?: T;
        readingMinutes?: T;
        bodyMarkdown?: T;
        id?: T;
      };
  webinars?:
    | T
    | {
        webinarId?: T;
        title?: T;
        speaker?: T;
        speakerRole?: T;
        startsAt?: T;
        durationMinutes?: T;
        level?: T;
        description?: T;
        id?: T;
      };
  glossary?:
    | T
    | {
        term?: T;
        definition?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-streams_select".
 */
export interface SiteStreamsSelect<T extends boolean = true> {
  site?: T;
  items?:
    | T
    | {
        provider?: T;
        videoId?: T;
        title?: T;
        poster?: T;
        startsAt?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contacts_select".
 */
export interface SiteContactsSelect<T extends boolean = true> {
  site?: T;
  channels?:
    | T
    | {
        title?: T;
        value?: T;
        detail?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        city?: T;
        country?: T;
        address?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-careers_select".
 */
export interface SiteCareersSelect<T extends boolean = true> {
  site?: T;
  benefits?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  vacancies?:
    | T
    | {
        title?: T;
        department?: T;
        location?: T;
        type?: T;
        applyEmail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-legal_select".
 */
export interface SiteLegalSelect<T extends boolean = true> {
  site?: T;
  items?:
    | T
    | {
        slug?: T;
        title?: T;
        updatedAt?: T;
        intro?: T;
        sections?:
          | T
          | {
              heading?: T;
              paragraphsMarkdown?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-system-status_select".
 */
export interface SiteSystemStatusSelect<T extends boolean = true> {
  site?: T;
  services?:
    | T
    | {
        serviceId?: T;
        name?: T;
        description?: T;
        status?: T;
        uptime90d?: T;
        id?: T;
      };
  incidents?:
    | T
    | {
        date?: T;
        title?: T;
        status?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-cabinet-home_select".
 */
export interface SiteCabinetHomeSelect<T extends boolean = true> {
  site?: T;
  modules?:
    | T
    | {
        type?: T;
        enabled?: T;
        steps?:
          | T
          | {
              verification?: T;
              deposit?: T;
              firstTrade?: T;
            };
        buttons?:
          | T
          | {
              deposit?: T;
              withdraw?: T;
              buyFiat?: T;
            };
        tabs?:
          | T
          | {
              assets?: T;
              popular?: T;
              newListing?: T;
              favorites?: T;
              gainers?: T;
              volume?: T;
            };
        newListingSymbols?:
          | T
          | {
              symbol?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}